### PR TITLE
Add initiator type to generated diagram

### PR DESCRIPTION
**Pull request by DBX12**
# Description

Color connections based on the value of `log.entries[]._initiator.type`

Relates to issue #9 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
_see checklist below_

# How Has This Been Tested?

- [x] Running existing tests
- [x] Created new tests

# Checklist:

- [ ] My code has been linted (`make lint`)
_I tried, but 4 linters are outdated, three of them without replacement. I'm optimistic and hope GoLand did a good job here_
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
_I've took the liberty to check this box as there was no documentation to add to and considered my change small enough to not require full documentation apart from the legend added to the generated puml code._
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have rebased my branch to include the latest changes from `master`

---
I'm participating in Hacktoberfest 2022. If you like this PR, I'd be glad if you could add the hacktoberfest-accepted label to it and help me reach my goal :)

### CODE REVIEW

**Comment by dnnrly** [comment]
I slightly tweaked the title to prevent closure of the issue because I think there's more can be done. BUT I like this PR!! Merged. :)

**Comment by DBX12** [comment]
Alright, thank you :)
Do you have any pointers on what more could be done? As I wrote on the issue, I could imagine showing additional data about the initiator when run with a command flag (like `--verbose-initiator`). What do you think?

**Comment by dnnrly** [comment]
> Alright, thank you :) Do you have any pointers on what more could be done? As I wrote on the issue, I could imagine showing additional data about the initiator when run with a command flag (like `--verbose-initiator`). What do you think?

Go for it!! I'm unlikely to be able to merge any PRs for the next week though.

**Comment by DBX12** [comment]
As long as you add the `hacktoberfest-accepted` label some point this week, all is fine :grin:

**Pull request merged**
